glpi-project/docdev

source/conf.py, source/plugins/hooks.rst
Follows https://github.com/glpi-project/glpi/pull/1674
=> Minified for plugins

source/devapi/index.rst, source/devapi/translations.rst
See http://glpi-developer-documentation.readthedocs.io/en/feature-translations/devapi/translations.html
=> A word on translations

source/devapi/dbmodel.rst, source/devapi/index.rst, source/devapi/mainobjects.rst
See http://glpi-developer-documentation.readthedocs.io/en/feature-main-objects/devapi/mainobjects.html
=> Document main objects; closes #18

source/devapi/index.rst, source/devapi/tools.rst
=> Document tools

source/devapi/dbmodel.rst, source/plugins/database.rst, source/plugins/guidelines.rst, source/plugins/index.rst, source/plugins/objects.rst, source/plugins/requirements.rst, source/plugins/tips.rst, source/sourcecode.rst
See http://glpi-developer-documentation.readthedocs.io/en/feature-plugins/
=> Improve plugins documentation; closes #3

source/devapi/acl.rst, source/devapi/index.rst
See: http://glpi-developer-documentation.readthedocs.io/en/acl/
=> add right management

source/codingstandards.rst
See http://glpi-developer-documentation.readthedocs.io/en/static-non-static/codingstandards.html#static-or-non-static
=> A word about static vs non static calls; fixes #41

source/devapi/dbmodel.rst
Related to https://github.com/glpi-project/glpi/pull/1939 and preceding IRC discussions.
=> A brief word on resultsets

source/plugins/index.rst, source/plugins/notifications.rst
Document adding notifications modes (see https://github.com/glpi-project/glpi/pull/2207). Should not be merged before the PR on the core has been as well.
View online:
http://glpi-developer-documentation.readthedocs.io/en/feature-notifs_modes/plugins/notifications.html
=> Document adding notification modes

source/devapi/crontasks.rst
=> update cron documentation

source/plugins/hooks.rst
Follows https://github.com/glpi-project/glpi/pull/2676
=> Add search hooks

source/devapi/search.rst
See https://github.com/glpi-project/glpi/pull/3061
=> add itemtype_item_revert

source/plugins/hooks.rst
=> Add doc for hook item_stats

source/devapi/database/dbupdate.rst
No preview available, build on rtfd is failing :/
=> A word about prepared statements

source/devapi/database/dbiterator.rst
As discussed on https://github.com/glpi-project/glpi/pull/3877
=> Add Bitwise AND on the operators

source/devapi/database/dbiterator.rst
RIGHT JOIN
Aggregate functions
ON as FKEY alias
=> Document new iterator capabilities

source/plugins/hooks.rst
See https://github.com/glpi-project/glpi/pull/4953
=> Add add_recipient_to_target hook documentation

source/devapi/database/dbiterator.rst
Updated fields selection part.
=> Update DBIterator doc to match new SELECT DISTINCT syntax

source/devapi/database/dbiterator.rst
add a complex example for criteria
=> add complex criteria example

source/plugins/tips.rst
On my tries on multitab `$tabnum` is zero based.
=> Multitab are zero based ?

source/sourcecode.rst
Added info and example for the -m option
=> Added the -m option

source/devapi/translations.rst
related to https://github.com/glpi-project/glpi/pull/6537
=> Add JS translations functions documentation

source/devapi/database/dbiterator.rst
Document new queryexpression usage introduced in GLPI 9.5.
To merge after the following PR is merged
https://github.com/glpi-project/glpi/pull/6199
=> document new queryexpression usage

Makefile, README.md, make.bat
Add autobuild target with `sphinx-autobuild` to match the user documentation repo.
=> Add autobuild

source/plugins/atoum.rst, source/plugins/index.rst, source/plugins/test.rst
Waiting for the Jamf plugin to add and push tests to GitHub since it is referenced in the new docs.
=> Add Atoum tests documentation

source/devapi/database/dbupdate.rst
just a small mistake in the example
=> Db prepared statements insert + select

source/plugins/hooks.rst
Relies on glpi-project/glpi#10214
=> Kanban filter hooks

source/plugins/hooks.rst
Feature: glpi-project/glpi#10412
=> Add helpdesk_menu_entry hooks

source/plugins/hooks.rst
Linked with https://github.com/glpi-project/glpi/pull/9834
=> Add doc for new hook show_in_timeline

source/plugins/requirements.rst
See https://github.com/glpi-project/glpi/pull/10944
=> `autoinstall_disabled` option documentation

source/sourcecode.rst
1. Document JavaScript unit testing (Jest)
2. Make minor improvements to existing PHP unit testing (atoum) documentation
=> Improve test documentation

source/devapi/database/dbmodel.rst, source/plugins/database.rst
MyISAM hasn't been supported since GLPI 9.4 and utfmb4 is now the recommended charset.
=> Update db engine, charset and collation

source/devapi/hlapi/index.rst, source/devapi/hlapi/schemas.rst, source/devapi/hlapi/search.rst
Documentation explaining the internal systems for the new API including schemas, search engine, routing, etc.
=> High-Level API Internals Documentation

source/devapi/index.rst, source/devapi/tools.rst
apigen DOT org is a dead site.
=> fix: apigen url

source/devapi/hlapi/index.rst, source/devapi/hlapi/schemas.rst, source/devapi/hlapi/versioning.rst
Document the internals of how the High-Level API handles API versions.
This is for GLPI PR glpi-project/glpi#17606
=> High-Level API Versioning Logic

source/upgradeguides/glpi-11.0.rst, source/upgradeguides/index.rst
See https://github.com/glpi-project/glpi/pull/17929
=> Add routing changes section to the GLPI 11.0 upgrade guidelines

source/upgradeguides/glpi-11.0.rst
cf https://github.com/glpi-project/glpi/pull/18126
=> Add migration guide related resource access restrictions

source/codingstandards.rst, source/sourcecode.rst
- **Update sourcecode testing section**
- **Update linting section**
- **nfo about launching tests "as in ci" + note about phpunit**
=> update tests documentation

source/plugins/requirements.rst, source/upgradeguides/glpi-11.0.rst
related to https://github.com/glpi-project/glpi/pull/20189 and https://github.com/glpi-project/glpi/pull/20333
=> Add documentation about stateless endpoints

source/devapi/search.rst
missing option `condition` doc.
=> add 'condition' field doc.

source/devapi/database/dbiterator.rst, source/plugins/hooks.rst, source/plugins/tutorial.rst
Fixing some typos and deprecated/removed glpi 11 methods
=> Fix small errors in plugin tutorial

source/devapi/hlapi/schemas.rst
Documentation change for https://github.com/glpi-project/glpi/pull/21167
=> [HLAPI] use readOnly and writeOnly
